global:
route:
  receiver: Default
  group_by: ['alertname'] #grupar por alertname
  group_wait: 15s #quanto tempo esperar antes de enviar a notificação
  group_interval: 15s #quanto tempo para enviar os alertas novamente depois de ja ter enviado
  repeat_interval: 1m #quanto tempo de tolerancia, pra enviar a mesma notificação novamente

  routes:
  - receiver: AlertaDatabase
    match:
      team: mongodb
  
  - receiver: AlertaWebApi
    match:
      team: webapi

receivers:
- name: Default
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookdefault'

- name: AlertaDatabase
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookmongodb'

- name: AlertaWebApi
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookwebapi'