version: '3,8'
services:
  api:
    image: kubedevio/pedelogo-catalogo:v1.0.0
    ports:
      - "8080:80"
    networks: 
      - pedelogo
    depends_on:
      - pedelogo-mongo
    environment:
      Mongo__Host: "pedelogo-mongo"
      Mongo__User: "mongouser"
      Mongo__Password: "mongopwd"
      Mongo__Port: "27017"
      Mongo__Database: "admin"

  pedelogo-mongo:
    image: mongo:4.4.2
    volumes:
      - db_mongo:/data/db
    ports:
      - "27017:27017"
    networks: 
      - pedelogo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  mongoexporter:
    image: fabricioveronez/mongo_exporter
    ports:
      - "9216:9216"
    networks: 
      - pedelogo
    depends_on:
      - pedelogo-mongo
    environment:
      MONGODB_URI: "mongodb://mongouser:mongopwd@pedelogo-mongo:27017"
  
  prometheus:
    image: prom/prometheus:v3.7.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
    networks: 
      - pedelogo

  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/prometheus/alertmanager.yml
    command:
      - "--config.file=/prometheus/alertmanager.yml"
    networks: 
      - pedelogo

volumes:
  db_mongo: 

networks:
  pedelogo:
    driver: bridge